"""empty message

Revision ID: 481c95eb0a13
Revises: 
Create Date: 2024-05-22 11:50:10.822516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481c95eb0a13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_types')),
    sa.UniqueConstraint('name', name=op.f('uq_article_types_name'))
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('download_link', sa.String(length=255), nullable=True),
    sa.Column('download_link2', sa.String(length=255), nullable=True),
    sa.Column('download_link3', sa.String(length=255), nullable=True),
    sa.Column('magnet_link', sa.String(length=255), nullable=True),
    sa.Column('magnet_link2', sa.String(length=255), nullable=True),
    sa.Column('magnet_link3', sa.String(length=255), nullable=True),
    sa.Column('torrent_link', sa.String(length=255), nullable=True),
    sa.Column('torrent_link2', sa.String(length=255), nullable=True),
    sa.Column('torrent_link3', sa.String(length=255), nullable=True),
    sa.Column('ipfs_link', sa.String(length=255), nullable=True),
    sa.Column('ipfs_link2', sa.String(length=255), nullable=True),
    sa.Column('ipfs_link3', sa.String(length=255), nullable=True),
    sa.Column('download_size', sa.String(length=255), nullable=True),
    sa.Column('external_collaboration', sa.String(length=255), nullable=True),
    sa.Column('external_collaboration2', sa.String(length=255), nullable=True),
    sa.Column('external_collaboration3', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('last_edited', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('pending_approval', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('slug', name=op.f('uq_articles_slug'))
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citations'))
    )
    op.create_table('invitation_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('used', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_invitation_codes_code'))
    )
    op.create_table('logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logos'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('include_in_team_page', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('custom_url', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('article_article_types',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('article_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_article_types_article_id_articles')),
    sa.ForeignKeyConstraint(['article_type_id'], ['article_types.id'], name=op.f('fk_article_article_types_article_type_id_article_types')),
    sa.PrimaryKeyConstraint('article_id', 'article_type_id', name=op.f('pk_article_article_types')),
    sqlite_with_rowid=False
    )
    op.create_table('article_categories',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_categories_article_id_articles')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_article_categories_category_id_categories')),
    sa.PrimaryKeyConstraint('article_id', 'category_id', name=op.f('pk_article_categories')),
    sqlite_with_rowid=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_categories')
    op.drop_table('article_article_types')
    op.drop_table('users')
    op.drop_table('logos')
    op.drop_table('invitation_codes')
    op.drop_table('citations')
    op.drop_table('categories')
    op.drop_table('articles')
    op.drop_table('article_types')
    # ### end Alembic commands ###
