"""increase sizes of more articles fields

Revision ID: 6938a905941f
Revises: d27d6236aaec
Create Date: 2024-07-01 17:00:29.321633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6938a905941f'
down_revision = 'd27d6236aaec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('download_link',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('download_link2',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('download_link3',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('magnet_link',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('magnet_link2',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('magnet_link3',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('torrent_link',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('torrent_link2',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('torrent_link3',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('ipfs_link',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('ipfs_link2',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('ipfs_link3',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('ipfs_link3',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('ipfs_link2',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('ipfs_link',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('torrent_link3',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('torrent_link2',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('torrent_link',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('magnet_link3',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('magnet_link2',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('magnet_link',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('download_link3',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('download_link2',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('download_link',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
